name: "Assert Branch Naming"

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    check-branch-name:
        runs-on: ubuntu-latest
        steps:
            - name: Check Branch Name
              uses: deepakputhraya/action-branch-name@master
              with:
                  # Regex for: type/description (e.g., feat/my-feature)
                  regex: '^(feat|fix|release|chore)\/[a-z0-9-]+$'
                  allowed_prefixes: "feat/,fix/,release/,chore/"
                  ignore: "main,develop"
