name: Test

on:
  workflow_call:
  # pull_request:
  #   paths:
  #     - "backend/**/*.go"
  #     - "backend/go.mod"
  #     - "backend/go.sum"
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "backend/**/*.go"
  #     - "backend/go.mod"
  #     - "backend/go.sum"

jobs:
  backend-test:
    name: backend-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum
          cache: true

      - name: Run tests
        run: go test ./...
        working-directory: backend

  golangci:
    name: backend-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: backend/go.mod
          cache: false

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          working-directory: backend
          args: ./...
          skip-cache: true
